import json
import os
import uuid
from datetime import datetime
from pathlib import Path

import streamlit as st
from dotenv import load_dotenv

from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_chroma import Chroma
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.messages import HumanMessage, AIMessage

DB_PATH = "vectorstore"
EMBEDDING_MODEL = "text-embedding-3-small"
CHAT_MODEL = "gpt-4o-mini"
TOP_K = 4
HISTORY_TURNS = 4
CRISIS_WINDOW_TURNS = 3   # crisis detection runs over the last N user turns (multi-turn build-up)
LOG_DIR = Path("logs")
LOG_DIR.mkdir(exist_ok=True)

# --- Base prompt (unchanged safety rules) ---
# Note: the knowledge base is in Dutch (NOV/Thuisarts). The model will answer
# in the language of the question; instruct it to reply in English by default.
SYSTEM_PROMPT = """You are ArtroseCoach, a supportive osteoarthritis self-management assistant.

How to respond:
- Always reply in English, even if the source documents are in another language. Translate any cited information naturally into English.
- For greetings, small talk, or questions about what you can do: respond naturally and briefly. Introduce yourself and what you can help with. You do not need to use the context for these.
- For substantive questions about osteoarthritis or self-management: answer based ONLY on the provided context.
- If a substantive question cannot be answered from the context, say you don't have information on that topic in your source materials and suggest the user consult a healthcare professional.

Rules you must follow:
- Do not diagnose conditions.
- Do not prescribe or recommend specific medications or dosages.
- Do not present yourself as a replacement for a doctor, physiotherapist, or other healthcare professional.
- Be warm, clear, and encouraging."""

USER_TEMPLATE = """Context from source documents:
{context}

Question: {question}"""

# Fixed crisis referral. Active in BOTH study conditions as a safety floor;
# deliberately NOT generated by the LLM (see Q3: conservative, source-side prevention).
# 113 Suicide Prevention has English-speaking operators; the generic line covers
# participants outside the Netherlands.
CRISIS_MESSAGE = (
    "It sounds like you are going through a really difficult time right now. "
    "I am only an information prototype and I cannot give you the help you deserve. "
    "Please talk to someone who can help. In the Netherlands you can reach 113 "
    "Suicide Prevention (free and anonymous, day and night) by calling 113 or "
    "0800-0113, or chat at 113.nl — English-speaking support is available. "
    "Outside the Netherlands, please contact your local crisis service. "
    "In case of immediate danger, call your local emergency number (112 in the Netherlands)."
)

# Shown on open as an in-app consent gate; the bot only proceeds after the user agrees.
CONSENT_TEXT = """**Consent to participate**

You are about to use a research prototype of ArtroseCoach, a chatbot that provides information on self-management of osteoarthritis. We will ask you to use the assistant and then answer a few short questions.

- Participation is **voluntary**; you may stop at any time, without giving a reason.
- ArtroseCoach is a **prototype and does not provide medical advice**. Do not act on its answers; for health-related questions, please consult your own doctor or physiotherapist.
- Your answers and the conversations are stored in **pseudonymised** form and used only for this research.
- Questions? Contact [researcher, email].
"""

# --- Signal detection for the two tiered questions (keyword-based, transparent first pass) ---
# Dutch terms retained for robustness; English equivalents added so detection
# works regardless of the language a participant uses.
CRISIS_TERMS = [
    # Dutch
    "zelfmoord", "zelfdoding", "suïcide", "suicide", "eind aan mijn leven",
    "een eind aan maken", "niet meer leven", "er niet meer zijn", "wil dood",
    "dood willen", "niet meer wakker worden", "uit het leven stappen",
    "niet meer verder", "mezelf iets aandoen", "mezelf wat aandoen",
    "mezelf pijn doen", "het niet meer zien zitten", "zie het niet meer zitten",
    "geen reden om door te gaan", "beter af zonder mij",
    # English
    "kill myself", "killing myself", "end my life", "ending my life",
    "want to die", "wanting to die", "wish i was dead", "wish i were dead",
    "don't want to live", "do not want to live", "no reason to live",
    "no reason to go on", "no point going on", "better off without me",
    "better off dead", "hurt myself", "harm myself", "self-harm", "self harm",
    "take my own life", "taking my own life", "not wake up",
    "can't go on", "cannot go on",
]
PSYCH_TERMS = [
    # Dutch
    "somber", "depressief", "depressie", "angstig", "hopeloos", "eenzaam",
    "alleen voel", "piekeren", "veel stress", "verdrietig", "geen zin meer",
    "nergens zin in", "geen energie", "moedeloos", "down voel", "voel me slecht",
    # English
    "depressed", "depression", "anxious", "anxiety", "hopeless", "lonely",
    "feel alone", "feeling alone", "worrying a lot", "very stressed",
    "stressed out", "sad", "feeling sad", "no motivation", "no energy",
    "feel down", "feeling down", "feel low", "feeling low", "feel bad",
    "feeling bad", "feel terrible", "feeling terrible", "burnt out",
    "burned out", "overwhelmed",
]
LITERACY_TERMS = [
    # Dutch
    "snap ik niet", "snap het niet", "begrijp ik niet", "te moeilijk",
    "te ingewikkeld", "ingewikkeld", "wat betekent", "kun je het simpeler",
    "simpeler", "makkelijker uitleggen", "versimpel", "geen idee wat",
    "moeilijke woorden", "lastig te begrijpen",
    # English
    "don't understand", "do not understand", "don't get it", "do not get it",
    "too difficult", "too complicated", "too complex", "what does that mean",
    "what does this mean", "can you simplify", "simpler", "make it simpler",
    "explain more simply", "easier words", "hard to understand",
    "hard to follow", "no idea what",
]


def detect_signals(text, recent_user_msgs=None):
    """Crisis detection runs over the current message plus the recent user turns
    (to catch multi-turn build-up / conversational drift, Q3); psych and literacy
    are judged on the current message only. Crisis takes precedence."""
    t = text.lower()
    crisis_scope = " ".join(recent_user_msgs).lower() if recent_user_msgs else t
    crisis = any(k in crisis_scope for k in CRISIS_TERMS)
    return {
        "crisis": crisis,
        "psych": (not crisis) and any(k in t for k in PSYCH_TERMS),
        "literacy": any(k in t for k in LITERACY_TERMS),
    }


def turn_directives(signals, personalized):
    """Tiered signal questions (psych + literacy) only fire in the personalized condition."""
    parts = []
    if personalized and signals["psych"]:
        parts.append(
            "\n\nThe user may be experiencing low mood, stress, or worry. Respond with empathy "
            "and gently ask one brief, non-clinical question about how they have been feeling "
            "emotionally lately. Do not diagnose. Encourage talking to their GP or a trusted "
            "person if the feelings persist."
        )
    if personalized and signals["literacy"]:
        parts.append(
            "\n\nThe user appears to find the information hard to follow. Answer in plain, simple "
            "language: short sentences, everyday words, a concrete example, and briefly check "
            "whether it is clear."
        )
    return "".join(parts)


def build_profile_block(p):
    """Render the intake profile into a compact tailoring instruction for the prompt."""
    if not p:
        return ""
    lines = [
        f"- Age {p['age']}, sex {p['sex']}.",
        f"- Weight {p['weight']} kg, height {p['height']} cm (BMI {p['bmi']}).",
        f"- Pain {p['pain_intensity']}/10, {p['pain_nature']}, duration: {p['pain_duration']}.",
        f"- Morning stiffness: {p['morning_stiffness']}.",
        f"- Affected joint: {p['joint']} ({p['joint_count']} joint(s)).",
        f"- Care pathway: {p['care_pathway']}.",
        f"- Work load: {p['work']}; activity level: {p['activity']}.",
    ]
    if p.get("limitations"):
        lines.append(f"- Limitations in daily life: {', '.join(p['limitations'])}.")
    if p.get("comorbidities"):
        lines.append(f"- Comorbidities: {', '.join(p['comorbidities'])}.")
    if p.get("medication"):
        lines.append(f"- Medication: {p['medication']}.")
    if p.get("tried"):
        lines.append(f"- Previously tried: {', '.join(p['tried'])}.")
    if p.get("sport"):
        lines.append(f"- Sport: {p['sport']}.")
    if p.get("goals"):
        lines.append(f"- Goals/preferences: {', '.join(p['goals'])}.")
    return (
        "\n\nThe user has completed an intake. Tailor your advice to the profile below: "
        "weigh relevant factors (e.g. affected joint, pain, weight, comorbidities, goals), "
        "refer to it naturally, do NOT list it back verbatim, and never present tailored "
        "information as a diagnosis. Keep all safety rules above.\nProfile:\n" + "\n".join(lines)
    )


@st.cache_resource
def get_chain():
    """Build retriever, LLM, and prompt once and cache across reruns."""
    load_dotenv()
    if not os.getenv("OPENAI_API_KEY"):
        st.error("OPENAI_API_KEY is not set. Add it to your .env file.")
        st.stop()
    embeddings = OpenAIEmbeddings(model=EMBEDDING_MODEL)
    db = Chroma(persist_directory=DB_PATH, embedding_function=embeddings)
    retriever = db.as_retriever(search_kwargs={"k": TOP_K})
    llm = ChatOpenAI(model=CHAT_MODEL, temperature=0)
    prompt = ChatPromptTemplate.from_messages([
        ("system", SYSTEM_PROMPT + "{profile_block}{turn_directives}"),
        ("placeholder", "{history}"),
        ("human", USER_TEMPLATE),
    ])
    return retriever, llm, prompt


def format_sources(docs):
    seen = []
    for d in docs:
        src = Path(d.metadata.get("source", "unknown")).name
        page = d.metadata.get("page")
        tag = f"{src} p.{page + 1}" if page is not None else src
        if tag not in seen:
            seen.append(tag)
    return seen


def log_turn(session_id, condition, question, sources, answer, signals):
    log_file = LOG_DIR / f"{datetime.utcnow().strftime('%Y-%m-%d')}.jsonl"
    record = {
        "timestamp": datetime.utcnow().isoformat(),
        "session_id": session_id,
        "condition": condition,                 # "personalized" | "control"
        "question": question,
        "sources": sources,
        "answer": answer,
        "signals": signals,                     # crisis / psych / literacy flags
    }
    with log_file.open("a", encoding="utf-8") as f:
        f.write(json.dumps(record) + "\n")


def resolve_condition():
    """Personalized vs control. Researcher sets it; a URL query param ?p=1 / ?p=0
    overrides (useful for blinded runs). Logged per turn."""
    params = st.query_params
    if "p" in params:
        return params["p"] not in ("0", "false", "no")
    return st.session_state.get("_personalized", True)


def render_intake_form():
    st.subheader("Short intake")
    st.caption("A few questions so the assistant can tailor its information to you.")
    with st.form("intake"):
        age = st.number_input("Age", 18, 100, 60)
        sex = st.selectbox("Sex", ["male", "female", "other", "prefer not to say"])
        c1, c2 = st.columns(2)
        weight = c1.number_input("Weight (kg)", 30, 250, 80)
        height = c2.number_input("Height (cm)", 120, 220, 175)
        pain_intensity = st.slider("Pain right now (0 = none, 10 = worst imaginable)", 0, 10, 5)
        pain_nature = st.selectbox("When do you mostly have pain?",
                                   ["mainly with activity", "also at rest", "varies"])
        pain_duration = st.selectbox("How long have you had complaints?",
                                     ["less than 6 weeks", "6 weeks to 3 months", "longer than 3 months"])
        morning_stiffness = st.selectbox("Morning stiffness",
                                         ["none", "less than 30 minutes", "longer than 30 minutes"])
        limitations = st.multiselect(
            "Where do you experience difficulty in daily life?",
            ["climbing stairs", "walking", "getting up/sitting down",
             "getting dressed", "work", "sport", "sleeping"])
        joint = st.selectbox("Which joint has the complaints?", ["knee", "hip", "both"])
        joint_count = st.selectbox("Number of affected joints", ["one", "multiple"])
        comorbidities = st.multiselect(
            "Do you have any of these conditions?",
            ["cardiovascular disease", "diabetes",
             "gastrointestinal problems", "kidney problems"])
        medication = st.text_input("Do you take medication for the complaints? (optional)")
        tried = st.multiselect(
            "What have you already tried?",
            ["exercise therapy/physiotherapy", "painkillers", "injection",
             "weight loss", "nothing yet"])
        care_pathway = st.selectbox(
            "Where are you currently?",
            ["not yet seen a doctor", "under treatment by GP",
             "referred to physiotherapy", "waiting for surgery", "other"])
        work = st.selectbox("What kind of load do you have during the day?",
                            ["mostly sedentary", "mostly standing/walking",
                             "heavy physical work", "not working"])
        activity = st.selectbox("How active are you typically?", ["low", "moderate", "high"])
        sport = st.text_input("Do you play any sports? (optional)")
        goals = st.multiselect(
            "What do you most want to achieve?",
            ["less pain", "better movement", "stay active at work", "be able to play sport",
             "less medication", "postpone surgery"])
        submitted = st.form_submit_button("Start the conversation")
    if submitted:
        bmi = round(weight / ((height / 100) ** 2), 1) if height else None
        st.session_state.profile = {
            "age": age, "sex": sex, "weight": weight, "height": height,
            "bmi": bmi, "pain_intensity": pain_intensity, "pain_nature": pain_nature,
            "pain_duration": pain_duration, "morning_stiffness": morning_stiffness,
            "limitations": limitations, "joint": joint, "joint_count": joint_count,
            "comorbidities": comorbidities, "medication": medication.strip(),
            "tried": tried, "care_pathway": care_pathway, "work": work,
            "activity": activity, "sport": sport.strip(), "goals": goals,
        }
        st.session_state.intake_done = True
        st.rerun()


def log_consent(session_id, condition):
    log_file = LOG_DIR / f"{datetime.utcnow().strftime('%Y-%m-%d')}.jsonl"
    record = {
        "timestamp": datetime.utcnow().isoformat(),
        "session_id": session_id,
        "condition": condition,
        "event": "consent_given",
    }
    with log_file.open("a", encoding="utf-8") as f:
        f.write(json.dumps(record) + "\n")


def render_consent_gate(condition):
    st.markdown(CONSENT_TEXT)
    agree = st.checkbox("I have read the above and I agree to participate.")
    if st.button("Continue"):
        if agree:
            st.session_state.consent_given = True
            log_consent(st.session_state.session_id, condition)
            st.rerun()
        else:
            st.warning("Please tick the box first to continue.")


# --- UI ---
st.set_page_config(page_title="ArtroseCoach", page_icon="🦴")
st.title("ArtroseCoach")
st.caption("A self-management assistant for osteoarthritis information.")

with st.expander("⚠️ Important — please read before using", expanded=True):
    st.markdown(
        "This is a research prototype developed as part of a thesis project. "
        "It provides **general information** about osteoarthritis self-management "
        "based on a curated set of source documents.\n\n"
        "**It is not medical advice.** It cannot diagnose, prescribe, or replace "
        "consultation with a doctor, physiotherapist, or other healthcare professional. "
        "If you have concerns about your health, please contact a qualified clinician.\n\n"
        "Conversations may be logged for research purposes."
    )

if "session_id" not in st.session_state:
    st.session_state.session_id = str(uuid.uuid4())
if "messages" not in st.session_state:
    st.session_state.messages = []
if "history" not in st.session_state:
    st.session_state.history = []
if "profile" not in st.session_state:
    st.session_state.profile = None
if "intake_done" not in st.session_state:
    st.session_state.intake_done = False
if "consent_given" not in st.session_state:
    st.session_state.consent_given = False

# When the condition is set via the URL (blinded participant runs), hide the
# researcher control entirely so the participant cannot see or change the version.
url_has_condition = "p" in st.query_params

with st.sidebar:
    st.markdown(f"**Session:** `{st.session_state.session_id[:8]}`")
    if not url_has_condition:
        # Researcher control, shown only for non-blinded runs. For a participant
        # session, open the app with ?p=1 (personalized) or ?p=0 (control).
        choice = st.radio("Version (researcher)", ["A", "B"], horizontal=True,
                          help="A = personalized, B = non-personalized. Set before the session.")
        st.session_state._personalized = (choice == "A")
    if st.button("Start new conversation"):
        st.session_state.session_id = str(uuid.uuid4())
        st.session_state.messages = []
        st.session_state.history = []
        st.session_state.profile = None
        st.session_state.intake_done = False
        st.session_state.consent_given = False
        st.rerun()

personalized = resolve_condition()
condition = "personalized" if personalized else "control"

# Consent gate: shown on open; the bot only proceeds after the user agrees.
if not st.session_state.consent_given:
    render_consent_gate(condition)
    st.stop()

# Gate the chat behind the intake in the personalized condition.
if personalized and not st.session_state.intake_done:
    render_intake_form()
    st.stop()

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        if msg.get("sources"):
            st.caption("Sources: " + ", ".join(msg["sources"]))

if question := st.chat_input("Ask a question about osteoarthritis self-management..."):
    st.session_state.messages.append({"role": "user", "content": question})
    with st.chat_message("user"):
        st.markdown(question)

    recent_user_msgs = [m["content"] for m in st.session_state.messages
                        if m["role"] == "user"][-CRISIS_WINDOW_TURNS:]
    signals = detect_signals(question, recent_user_msgs)

    with st.chat_message("assistant"):
        # Safety floor: crisis handling is unconditional and not LLM-generated.
        if signals["crisis"]:
            answer = CRISIS_MESSAGE
            sources = []
            st.markdown(answer)
        else:
            retriever, llm, prompt = get_chain()
            with st.spinner("Looking it up..."):
                docs = retriever.invoke(question)
                if not docs:
                    answer = ("I don't have information on that in my source materials. "
                              "For questions outside these materials, please consult a "
                              "healthcare professional.")
                    sources = []
                else:
                    context = "\n\n".join(d.page_content for d in docs)
                    sources = format_sources(docs)
                    profile_block = build_profile_block(st.session_state.profile) if personalized else ""
                    directives = turn_directives(signals, personalized)
                    messages = prompt.format_messages(
                        profile_block=profile_block,
                        turn_directives=directives,
                        history=st.session_state.history[-HISTORY_TURNS * 2:],
                        context=context,
                        question=question,
                    )
                    try:
                        response = llm.invoke(messages)
                        answer = response.content
                    except Exception as e:
                        answer = f"Sorry, something went wrong: {e}"
                        sources = []
            st.markdown(answer)
            if sources:
                st.caption("Sources: " + ", ".join(sources))

    st.session_state.messages.append({"role": "assistant", "content": answer, "sources": sources})
    st.session_state.history.append(HumanMessage(content=question))
    st.session_state.history.append(AIMessage(content=answer))
    log_turn(st.session_state.session_id, condition, question, sources, answer, signals)